language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - "pypy3"
env:
  - PIP_VAL="pip install werkzeug==1.0.0"
  - PIP_VAL="pip install werkzeug==0.16.1"
  - PIP_VAL="pip install werkzeug==0.15.6"
  - PIP_VAL="pip install werkzeug==0.14.1"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-mock
  - pip install codecov
  - pip install pytest-timeout
install:
  - $PIP_VAL
script: pytest # run tests
after_success:
  - codecov # submit coverage

jobs:
  exclude:
  - python: 3.4
    env: PIP_VAL="pip install werkzeug==1.0.0"
